### ISSUE TITLE
Réponse à question à revoir

### ISSUE THREAD

**Issue by LeTank** [TruAcademy/TruAcademy#18]
La suggestion de réponse 3 me semble pas être la bonne !
<img width="1143" alt="capture d ecran 2016-02-09 a 15 57 18" src="https://cloud.githubusercontent.com/assets/13089062/12920123/a9af885c-cf47-11e5-9106-96f3daaccc6e.png">

**Comment by gealex** [comment]
La bonne réponse, c'est pas la 2 du coup ? Je retrouve plus le quizz pour ce module ...

**Comment by LeTank** [comment]
Laisse !
J'ai lu trop vite, je pensais que c'était une redite de la question ;)
