### ISSUE TITLE
Mettre les liens URL en violet

### ISSUE THREAD

**Issue by LeTank** [TruAcademy/TruAcademy#25]
<img width="485" alt="capture d ecran 2016-02-15 a 18 08 18" src="https://cloud.githubusercontent.com/assets/13089062/13055448/b28c6e6e-d40f-11e5-8784-4dc78223d16e.png">

**Comment by gealex** [comment]
![screen shot 2016-02-15 at 18 43 05](https://cloud.githubusercontent.com/assets/11295288/13056187/08d24600-d414-11e5-9aef-fa0d754e99fa.png)

J'ai mis les liens en bleu car ça me semblait bizarre en violet. Si il n'y a pas de couleur, c'est qu'il n'y a pas de lien et que je n'ai pas vu qu'il fallait mettre un lien dans le fichier de wording.

**Comment by LeTank** [comment]
Cool !
Violet était une suggestion ;)
